steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*************** TERRAFORM INIT ******************"
      echo "*************************************************"
      echo "current dir: `pwd`"
      echo "contents dir: `ls`"
      cd IaC
      terraform init 
      cd ..
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*************** TERRAFOM PLAN ******************"
      echo "*************************************************"
      echo "current dir: `pwd`"
      echo "contents dir: `ls`"
      cd IaC
      terraform plan 
      cd ..
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*************** TERRAFOM APPLY ******************"
      echo "*************************************************"
      echo "current dir: `pwd`"
      echo "contents dir: `ls`"
      cd Iac
      terraform apply -auto-approve
      cd ..
# [END tf-apply] 