steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*************** TERRAFORM INIT ******************"
      echo "*************************************************"
      terraform init 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*************** TERRAFOM PLAN ******************"
      echo "*************************************************"
      terraform plan 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.3.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*************** TERRAFOM APPLY ******************"
      echo "*************************************************"
      terraform apply -auto-approve
# [END tf-apply] 